### ISSUE TITLE
unclear where PR's should go.

### ISSUE THREAD

**Issue by magnetophon** [ech2/airwindows-ports#2]
I did [a PR](https://github.com/airwindows/airwindows/pull/5) that maybe should've gone here.
Please enlighten me!  :)

**Comment by ech2** [comment]
Well, this was the repo I experimented with the Linux build in the first place. IIUC, your PR was about Chris messed up the repository by pushing temporary files and stuff. I have some pans to experiment with better building, but don't have much time lately.

**Comment by magnetophon** [comment]
OK, so IIUC, the PR is in the correct place?

**Comment by ech2** [comment]
I think so :)

**Comment by ech2** [comment]
@magnetophon I noticed that you’re trying to include the plugins into NixOS (https://github.com/NixOS/nixpkgs/pull/45430). If that’s the case, it may be simpler to do it through this repo, as I suspect Chris just isn’t fluent with build systems and stuff related.

**Comment by magnetophon** [comment]
Yes, I'd like this to be in NixOS, but the vst licence is a bit of a put-off.

>  it may be simpler to do it through this repo (at least initially)

What do you mean? The PR, or basing the pkg off of this repo?
